server:
  port: 9000

spring:
  profiles:
    active: native
  application:
    name: CONFIG-SERVER
# not needed
#  zipkin:
#    base-url: http://localhost:9411/zipkin/

#not needed when using annotation in main class
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
# not needed
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost