server:
  port: 9191

#not needed when using annotation in main class
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#   not needed
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

management:
  tracing:
    sampling:
      probability: 1.0