server:
  port: 9002


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
# not needed
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  tracing:
    sampling:
      probability: 1.0